/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as MesTicketsRouteImport } from './routes/mes-tickets'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminMatchesRouteImport } from './routes/admin/matches'
import { Route as AdminCompetitionsRouteImport } from './routes/admin/competitions'

const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const MesTicketsRoute = MesTicketsRouteImport.update({
  id: '/mes-tickets',
  path: '/mes-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMatchesRoute = AdminMatchesRouteImport.update({
  id: '/admin/matches',
  path: '/admin/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompetitionsRoute = AdminCompetitionsRouteImport.update({
  id: '/admin/competitions',
  path: '/admin/competitions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/competitions': typeof CompetitionsRoute
  '/contact': typeof ContactRoute
  '/mes-tickets': typeof MesTicketsRoute
  '/scan': typeof ScanRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/competitions': typeof CompetitionsRoute
  '/contact': typeof ContactRoute
  '/mes-tickets': typeof MesTicketsRoute
  '/scan': typeof ScanRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/competitions': typeof CompetitionsRoute
  '/contact': typeof ContactRoute
  '/mes-tickets': typeof MesTicketsRoute
  '/scan': typeof ScanRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/competitions'
    | '/contact'
    | '/mes-tickets'
    | '/scan'
    | '/admin/competitions'
    | '/admin/matches'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/competitions'
    | '/contact'
    | '/mes-tickets'
    | '/scan'
    | '/admin/competitions'
    | '/admin/matches'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/competitions'
    | '/contact'
    | '/mes-tickets'
    | '/scan'
    | '/admin/competitions'
    | '/admin/matches'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CompetitionsRoute: typeof CompetitionsRoute
  ContactRoute: typeof ContactRoute
  MesTicketsRoute: typeof MesTicketsRoute
  ScanRoute: typeof ScanRoute
  AdminCompetitionsRoute: typeof AdminCompetitionsRoute
  AdminMatchesRoute: typeof AdminMatchesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes-tickets': {
      id: '/mes-tickets'
      path: '/mes-tickets'
      fullPath: '/mes-tickets'
      preLoaderRoute: typeof MesTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/matches': {
      id: '/admin/matches'
      path: '/admin/matches'
      fullPath: '/admin/matches'
      preLoaderRoute: typeof AdminMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/competitions': {
      id: '/admin/competitions'
      path: '/admin/competitions'
      fullPath: '/admin/competitions'
      preLoaderRoute: typeof AdminCompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CompetitionsRoute: CompetitionsRoute,
  ContactRoute: ContactRoute,
  MesTicketsRoute: MesTicketsRoute,
  ScanRoute: ScanRoute,
  AdminCompetitionsRoute: AdminCompetitionsRoute,
  AdminMatchesRoute: AdminMatchesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
